### ISSUE TITLE
minivi.ml domain for the project.

### ISSUE THREAD

**Issue by cljoly** [sd65/MiniVim#10]
I’m currently owning minivi.ml, and it’s set up to redirect to your Github page.

If you want to manage it yourself, drop me an email ([everything here](http://oclaunch.eu.org/contact)), and I will give it to you @sd65. However, since I couldn’t find the way to transfer it (actualy, it seems impossible for free domains), I would cancel it at a given time, with you ready to take it asap.

**Comment by sd65** [comment]
Hi,
This is kind to think about this!
Do you think it will be interesting to have a dedicated Github page with "How to use it" and minivi.ml redirecting to it?

**Comment by cljoly** [comment]
A page to promote the project, explaining why using it and how to use it would be interesting. The short url is great to share the page on social network, and thus, a "marketing" page behind minivi.ml may be great.

It’s even possible to use freenom DNS to make the page available without redirection.

**Comment by sd65** [comment]
Apparently there is no need for the moment. I'm closing for now but won't hesitate to contact you if I change my mind.

Thanks again kind stranger!

**Comment by cljoly** [comment]
I have registered the domain until 11/03/2018. I do not plan to renew it after this date, so it will be back to the wild. After that date, no need to contact me any more, except if you think I can help you with something.
