### ISSUE TITLE
[Resolved] Issue with file saving

### ISSUE THREAD

**Issue by tchaly-bethmaure** [sd65/MiniVim#14]
Hi,

When I press Ctrl + S vim (in MiniVim mode) doesn't save my file nor displaying something : it does nothing. I'm doing anything wrong or is it not working ?

Tchaly

**Comment by sd65** [comment]
Hi,
Sorry to hear about that, have you added the following line in your shell config (.bashrc, .zshrc...)?
`stty -ixon`
Then, open a new terminal and try again.

**Comment by tchaly-bethmaure** [comment]
Beautiful ! adding `stty -ixon` in my .zshrc worked well, Ctrl + S is now saving my file. 

Thank you !
