### ISSUE TITLE
Little issue with the number version

### ISSUE THREAD

**Issue by Wes974** [sd65/MiniVim#15]
Hi,

First, great work for what you have done !
But there is a little issue that I get when I launch vim (I'm on a Mac with OS X 10.11.3)
When I launch vim I got this :

![capture d ecran 2016-03-19 a 00 50 50](https://cloud.githubusercontent.com/assets/7169107/13891825/e1d612e4-ed6c-11e5-9c85-453418bb91d3.png)

It's seems that there is a little issue with the number version. It's not a very important issue, I just press enter, but I thought thats I should tell you. For now I just correct it by changing the number version to 1. But otherwise, everything works great, thank you !

**Comment by Wes974** [comment]
I have just created this pull request : #16 with this there won't be any more issue I think

**Comment by sd65** [comment]
Merged !
