### ISSUE TITLE
Fuzzy file search

### ISSUE THREAD

**Issue by edorgeville** [sd65/MiniVim#17]
First of all, great job ! It looks and feels great.
An option I really like and use with Sublime is the Ctrl+P option that let's you do a fuzzy search in the current directory (when you start it with `subl .`). Do you think it would be implementable ?

**Comment by sd65** [comment]
Hi, thanks!
You can do it with the following plugin :
[Ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim)
I think I will not integrate it into MiniVim for two reasons : I don't use this feature and the code will be significantly bigger with this feature.
Let me know if this plugin fits your needs. :-)
