### ISSUE TITLE
Document how to add plugins in a MiniVim relevant way

### ISSUE THREAD

**Issue by victornoel** [sd65/MiniVim#19]
I know the objective of MiniVim is not to use plugins, but it can be useful sometime to be able to do it, preferably with a plugin manager that combines well with Minivim.

I'm not a vim expert so I'm not even sure how to do that, so I thought maybe we could document it on the main page of minivim :)

**Comment by sd65** [comment]
That's an idea. I was thinking about this for some months but definitely want this to be part of MiniVim.
Stay tuned !

**Comment by sd65** [comment]
I added a new install that make the .vimrc much easier to hack.

Please delete your .vimrc and re-install the latest MiniVim.
Then look at any plugin you like and edit the .vimrc as you like !

Tell me if this is convenient and solved your concerns.

**Comment by victornoel** [comment]
Ok, some improvement maybe:
- it would be best if the .vimrc directly sourced the vimrc in the cloned repository because like this it will be easier to do updates

Then I can just setup a plugin manager by myself if I understood well :)

**Comment by sd65** [comment]
That's an idea. However, some users may delete the cloned repo or rename a parent dir and it will lead to an error in the .vimrc. Furthermore, the automated script take care of new versions automatically. 

You're totally right, setup a plugin manager has never been easier with the latest release !

**Comment by victornoel** [comment]
Ok, and also, there was another improvement possible: to move the potential configuration options that are at the head of the minivim vimrc into ~/.vimrc, so that custom configuration of minivim are kept inbetween updates :)

**Comment by sd65** [comment]
That's a nice idea ;-)

**Comment by sd65** [comment]
Done in the latest commit !
bc48ab5c597168d64d72747befe22c8744ca4849

Please let me know what you think.

**Comment by victornoel** [comment]
It seems to work well, thanks :)
