### ISSUE TITLE
I can't save in sudo 

### ISSUE THREAD

**Issue by kasuke5** [sd65/MiniVim#21]
Hello, something really strange happened when I'm in sudo.
When I type Ctrl + S, vim just freeze and do I can't do nothing in vim... It's really disturbing and I don't know what to do

**Comment by sd65** [comment]
Hi,

I'm glad you use MiniVim but you should have read the instructions !
[Manual Setup](https://github.com/sd65/MiniVim#manual-setup) and also this [this issue.](https://github.com/sd65/MiniVim/issues/14)

Fix your shell config, good luck :+)

**Comment by sd65** [comment]
My bad, it's more complicated. I'm on this.

**Comment by sd65** [comment]
Here it is :
[Instructions in README](https://github.com/sd65/MiniVim/blob/master/README.md#how-to-use-minivim-with-sudo)

Tell me if this helped you !

**Comment by kasuke5** [comment]
Yeah, I'm kind of noob I didn't know that I could see the old issues.
Thanks, but I just delete my .vimrc because I had things to do quickly with a functional vim :D I will try after and tell you
