### ISSUE TITLE
Ctrl H - Backspace

### ISSUE THREAD

**Issue by Antalis** [sd65/MiniVim#22]
Hi,

> "Ctrl H - Search and Replace
> call CreateShortcut("C-h", ":%s/", "in", "noTrailingIInInsert")`

Traditionally, CTRL-H is for "backspace key" and deletes the character that is left of the cursor.
That does not seem to me convenient to use to search .

**Comment by sd65** [comment]
Hi,

Sorry for the delay. I understand your point and knew Ctrl-H could be used for backspace.
However, it's the shortcut used by Sublime Text for _Search and Replace_. I got used to it, etc.

What I suggest to you is to install MiniVim normally, then override/unbind the Ctrl-H like this

```
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MiniVim
" Details on : https://github.com/sd65/MiniVim
let g:MiniVimVersion = "1.3.3"
let g:UseCustomKeyBindings = 1
source $HOME/.vim/MiniVim.vimrc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"" Override here
map <C-H> X 
" or 
unmap <C-H>
" or anything you want with this key
```

:-)
