### ISSUE TITLE
MiniVim corrupts Vim for Windows interface

### ISSUE THREAD

**Issue by jonathanlinat** [sd65/MiniVim#24]
The newer version of MiniVim corrupts my Vim for Windows interface.

![cmder_2](https://cloud.githubusercontent.com/assets/14064112/18930286/74294bbe-8595-11e6-850c-d43b15c4b997.jpg)

I installed the .vimrc manually and also with the automated script (./install.sh).

**Comment by joeky888** [comment]
add

```
set term=vt100
set t_Co=256
let &t_AB="\e[48;5;%dm"
let &t_AF="\e[38;5;%dm"
```

to your .vimrc

[https://www.reddit.com/r/vim/comments/3r6zvz/cmder_vim_syntax_highlighting/](https://www.reddit.com/r/vim/comments/3r6zvz/cmder_vim_syntax_highlighting/)

[http://unix.stackexchange.com/questions/23764/changing-terminal-emulators](http://unix.stackexchange.com/questions/23764/changing-terminal-emulators)

Also, I recommend Msys2+tmux OR Cygwin+tmux.
Cmder is fancy but lack of maintainers and functionalities for me.

**Comment by sd65** [comment]
Is the solution of @j16180339887 working for you ?

**Comment by jonathanlinat** [comment]
@sd65 Nope. @j16180339887's solution didn't work.

**Comment by sd65** [comment]
@jonathanlinat OK, can you provide me steps to reproduce the bug ?

You're on Windows with Cmder using SSH ?

**Comment by joeky888** [comment]
How about

```
if !has("gui_running")
  set term=vt100
  set nocompatible
  syntax on
endif
```

![image](http://i.imgur.com/J7XHVqy.png)

[http://conemu.github.io/en/VimXterm.html](http://conemu.github.io/en/VimXterm.html)

**Comment by jonathanlinat** [comment]
@j16180339887 Nope. This doesn't work. I just copy and paste the vimrc file content from Raw Github view to Windows Notepad and save it. Then I add this piece of code you gave me but Vim cannot locate vt100.

![cmder](https://cloud.githubusercontent.com/assets/14064112/19113788/93e080fc-8ae1-11e6-95bc-4b69b7737f5e.jpg)

I uninstalled and installed again cmder from scratch but I have the same problem.

![vim_corrupted](https://cloud.githubusercontent.com/assets/14064112/19114252/8fbb50b8-8ae3-11e6-92be-244891389661.png)

And I used the install.sh file also.

**Comment by joeky888** [comment]
Have you tried

`set term=vt320`

```
if !has("gui_running")
  set term=vt320
  set nocompatible
  syntax on
endif
```

![](http://i.imgur.com/ijOXcQH.png)
This works for me as well.

**Comment by jonathanlinat** [comment]
![vimrc_vt320](https://cloud.githubusercontent.com/assets/14064112/19123580/914868ae-8b05-11e6-970c-11bfe27fd701.gif)

This is what I get now with vt320.

**Comment by joeky888** [comment]
I can't reproduce that.
Maybe just reset the color of line number

```
if !has("gui_running")
  set term=vt320
  set nocompatible
  syntax on
  highlight LineNr ctermfg=grey
endif
```

**Comment by sd65** [comment]
I tried myself and couldn't make it work. 
According to [this](https://www.reddit.com/r/vim/comments/3r6zvz/cmder_vim_syntax_highlighting/) and [that](https://github.com/cmderdev/cmder/issues/846), this is not a MiniVim problem. I guess it's hard to have Windows, Cmder and Vim with colors.

You can use cmd, try mintty or get Windows 10 & Bash. 😄

**Comment by joeky888** [comment]
Hi @jonathanlinat . I know it's been a while but I've solved this.

It's because that when you are using cmder or powershell, 

your vim shell will be set to `C:\WINDOWS\system32\cmd.exe`

You can check this by typing `:set shell?` in vim.

cmd and powershell support only 16 colors while monokai is a 256 colors theme.

You can try my fork of Minivim.

https://github.com/j16180339887/vimrc

Screenshot of cmder

![vim](https://i.imgur.com/sLTpwYJ.png)

Screenshot of powershell

![vim](https://i.imgur.com/U8YohNS.png)

Screenshot of cmd.exe

![vim](https://i.imgur.com/dBYGnQ4.png)

**Comment by jonathanlinat** [comment]
Oh great! Thank you @j16180339887

**Comment by joeky888** [comment]
I forgot to mention that I am not using vim from cmder but from the official vim.

https://github.com/vim/vim-win32-installer/releases

![vim](https://i.imgur.com/gI95ASR.png)
