### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by lilp69** [sd65/MiniVim#28]
Hi, how to change color with minivim?
Cause colors aren't well done.
I can't see comment in my file cause they're in dark color.

**Comment by sd65** [comment]
Hi,

"Colors" are in fact called "colorschemes" in Vim.
And yes, I bundle a theme with Minivim. To change them you can :
- Delete the lines from `"""" Color Scheme` to the end in the MiniVim source file to revert to the vanilla Vim
- Change the colorscheme at run time by using `:colorscheme default` by example

Let me know if this works for you ;-)

**Comment by joeky888** [comment]
Unless you are using FreeBSD,
You can always get 256 colors support for vim if you are using Linux/macOS/Cygwin/Android.

## With GUI
If you're using terminal emulator, such as gnome-terminal/xterm/iTerm2/mintty/Termux(Android)

Add this code to your `.bash_profile` or `.bashrc` or `.zshrc`
```
if [[ "$TERM" == "xterm"* ]]; then
  export TERM=xterm-256color
fi
```

## Without GUI
If you're using tty, no GUI, no X server, such as Ubuntu Server/Arch linux/Manjaro.
You can still get 256 colors by installing `tmux` and `fbterm`.

Add this code to your `.bash_profile` or `.bashrc` or `.zshrc`
```
# Check if fbterm is installed
if [ $(command -v fbterm) ] ; then
      exec fbterm -- bash -c 'TERM=fbterm tmux'
else
      exec tmux
fi
```

## FreeBSD without GUI
No solution. you have to remove color themes in `.vimrc` .

**Comment by sd65** [comment]
Closing due to no update and great sum up of @j16180339887.
