### ISSUE TITLE
Minimap overview like in Sublime Text

### ISSUE THREAD

**Issue by piwig** [sd65/MiniVim#3]
It could be nice to have a minimap overview like in sublime:
https://github.com/severin-lemaignan/vim-minimap

Minivim is great by the way :) :+1:

**Comment by sd65** [comment]
Thanks! The minimap is an awesome feature that I sure like. Note that the implementation you linked rely on a python lib, I can't integrate this into MiniVim because I want to keep one file only.
However, I will look what I do to develop a similar feature. I keep you tuned here!

**Comment by sd65** [comment]
I investigated and it's impossible to realize in a terminal without external libs (as vim-minimap).
I guess MiniVim will never get that :confused: , but you are encouraged to create a custom .vimrc where you source MiniVim and vim-minimap !
