### ISSUE TITLE
Source personnal config

### ISSUE THREAD

**Issue by BugsyLansky** [sd65/MiniVim#4]
It could be nice if we could add customization in another file, with something like: 

```
try
source ~/.vim/my_configs.vim
catch
endtry
```

at the end of the .vimrc

**Comment by sd65** [comment]
Yes of course but I'm not sure to see the point to integrate this by default. 
You think this could prevent merge conflits when you update MiniVim with your customization?
Please elaborate ;-)

**Comment by BugsyLansky** [comment]
Yes, that's the point.
If you want to add commands or plug-ins, you don't want to see them deleted by an update !

**Comment by sd65** [comment]
Ok. I brainstormed about this. I was about to do it when I thought it will be easier in the following way:

If you want to add something to your vim, create your own .vimrc and in this file, source MiniVim. In this way, you control what is sourced and when.

Exemple:

_.vimrc_

```
" My options here

" I source MiniVim now
source ~/.miniVim.vim

" Here I add what I want.
```
