### ISSUE TITLE
Public key issue with automated setup

### ISSUE THREAD

**Issue by ghost** [sd65/MiniVim#7]
Hello!

I tried to install miniVim with the automated setup, but it returned this error:

> ```
> Cloning into 'MiniVim'...
> Permission denied (publickey).
> fatal: The remote end hung up unexpectedly
> ```

Any idea why?
Meanwhile I’ll try the manual setup…

Thanks for sharing this with the world! ;)
.V

**Comment by wtoscer** [comment]
Hello,
I think you must do it with https clone instead of ssh
Or you can add a public key to your github account ( https://github.com/settings/ssh )

**Comment by sd65** [comment]
Thanks for pointing out this, cloning with HTTPS is by the way recommended!
